#Sources 
:sources: 
  Contact: 
    :poll_interval: 300
 
:test: 
  :syncserver: http://localhost:9292/application/
  :redis: localhost:6379
  :licensefile: settings/license.key
  :oraclecrm_service_url: https://secure-ausomxkwa.crmondemand.com/Services/Integration
  :username: example_user
  :password: sword1
:production: 
  :syncserver: http://localhost:9292/application/
  :redis: localhost:6379
  :licensefile: settings/license.key
  :oraclecrm_service_url: https://secure-ausomxkwa.crmondemand.com/Services/Integration
:development: 
  :syncserver: http://localhost:9292/application/
  :redis: localhost:6379
  :licensefile: settings/license.key
  :oraclecrm_service_url: https://secure-ausomxkwa.crmondemand.com/Services/Integration

