--- 
name: crmclient
extensions: 
- rhodes_translator
bbver: 4.6
wp: 
  productid: 1e9f3c80-737f-012e-9bec-60f84714f3cc
sdk: /Users/mzverev/.rvm/gems/ruby-1.8.7-p352/gems/rhodes-3.3.2
build: debug
applog: rholog.txt
version: 1.0
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
sdkversion: 3.0.0
vendor: rhomobile
iphone: 
  provisionprofile: 
  BundleURLScheme: crmclient
  BundleIdentifier: com.rhomobile.crmclient
  sdk: iphonesimulator4.3
  codesignidentity: 
  entitlements: 
  configuration: Debug
