sdk: "/Library/Ruby/Gems/1.8/gems/rhodes-3.0.0"
sdkversion: 3.0.0
name: crmclient
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator4.3
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.crmclient
  BundleURLScheme: crmclient
wp:
  productid: '1e9f3c80-737f-012e-9bec-60f84714f3cc'

extensions: ["json", "rhodes_translator"]
