--- 
extensions: 
- json
- rhodes_translator
name: crmclient
wp: 
  productid: 1e9f3c80-737f-012e-9bec-60f84714f3cc
bbver: 4.6
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-3.0.2
applog: rholog.txt
build: debug
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
vendor: rhomobile
sdkversion: 3.0.0
iphone: 
  BundleURLScheme: crmclient
  provisionprofile: 
  BundleIdentifier: com.rhomobile.crmclient
  sdk: iphonesimulator4.3
  entitlements: 
  codesignidentity: 
  configuration: Debug
